# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 13

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: $2y$13$VMgrRYPzes4qih2Kja8KAO1/YTHIhhJeEtFZjsGNgDgDvRGKHo88C
                        roles: ['ROLE_ADMIN']

    firewalls:
        admin_secure_area:
            pattern: ^/admin/
            http_basic:
                realm: "Secure admin area"

    access_control:
        - { path: ^/admin/, roles: ROLE_ADMIN }
